Feat: add new integrated vcs info to env0_environment data source
env0/terraform-provider-env0 pull request #587
Opened 2023-02-10 02:57 UTC by TomerHeber

### Issue & Steps to Reproduce / Feature Request
resolves #586 

### Solution

1. Added data fields in environment schema.
2. Updated acceptance tests.

2023-02-10 02:58 UTC, TomerHeber commented on client/template.go
> +	GitlabProjectId      int              `json:"gitlabProjectId,omitempty" tfschema:",omitempty"`
Missing from the API. It will need to be fixed in the backend.
Adding it... once fixed it will work properly.

2023-02-10 02:59 UTC, TomerHeber commented on env0/data_environment.go
> +	templateUpdater := struct {
creating this struct allows me to use the writeResourceData.

2023-02-14 08:33 UTC, eladmosh approved these changes

2023-02-14 09:49 UTC, eladmosh requested changes
@TomerHeber I approved your PR but we decided to implement `gitlab_project_id`, can you please remove it from the `env0_template` data source and from `env0_environment` data source (that you added now)

2023-02-14 15:27 UTC, eladmosh approved these changes

2023-02-14 15:28 UTC, merged